import { fileURLToPath } from 'node:url';

import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';

export default defineConfig({
	plugins: [react()],
	resolve: {
		alias: {
			// Generated by `vite-plugin-pwa` at build time, so it does not exist
			// here. Without the stub, any test that renders the root route fails
			// to resolve it. See `tests/stubs/pwa-register.ts`.
			'virtual:pwa-register/react': fileURLToPath(
				new URL('./tests/stubs/pwa-register.ts', import.meta.url)
			),
		},
	},
	test: {
		// Store tests only need fake-indexeddb; the editor and component tests
		// need a DOM, and jsdom is enough for CodeMirror at the dispatch level.
		environment: 'jsdom',
		include: ['tests/**/*.test.ts', 'tests/**/*.test.tsx'],
		setupFiles: ['./tests/setup.ts'],
	},
});
