/**
 * `virtual:pwa-register/react` is generated by `vite-plugin-pwa` at build time
 * and does not exist under Vitest, so any test that renders the root route —
 * which mounts `UpdatePrompt` — cannot resolve it. Aliased in `vitest.config.ts`.
 *
 * There is no service worker in a test, so there is never an update to offer.
 */
export const useRegisterSW = () => ({
	needRefresh: [false, () => undefined] as [boolean, (value: boolean) => void],
	offlineReady: [false, () => undefined] as [boolean, (value: boolean) => void],
	updateServiceWorker: () => Promise.resolve(undefined),
});
